### ISSUE TITLE
[CONQ] Lock status for controlpoints

### ISSUE THREAD

**Issue by Fisico** [teeworlds-domination/domination#11]
The first controlpoints from a team should have the status locked. This should focus the gameplay on the important controlpoints. It is also required for "spawn per controlpoint #8 ".

**Comment by Fisico** [comment]
Further refinements for locking mechanics and spawns. This includes removing the neutral state in the capturing process. 

- Start of the game: A and B Team Red, D and E Team Blue, State Locked. Control point C Neutral.
- After spot C got captured, unlock 2 control points. Always 2 control points should be open for capturing.
- Spawn is always at the teams latest owned and locked control point.
 

![image](https://user-images.githubusercontent.com/329471/50560091-6c046f80-0cfd-11e9-9008-ff38ccf7cb80.png)

**Comment by sepulzera** [comment]
Implemented with c5a13d68 -> closed.
