### ISSUE TITLE
Show capture progress in broadcast

### ISSUE THREAD

**Issue by Fisico** [teeworlds-domination/domination#12]
![image](https://user-images.githubusercontent.com/329471/50538924-2cf8e180-0b78-11e9-9936-237875eb9db2.png)

Point A: Blue Team in progress to capture Red Point 
Point B: Blue Team in progress to captures Neutral Point 
Point C: Capture Point is owned by Team Blue
Point E and E: Capture Point is owned by Team Blue and is locked.

Colored broadcast is required. Show MOTD, server msg and a broadcast to user to activate it.

**Comment by sepulzera** [comment]
After our most recent discussion about the lock behaviour, the shown image is incorrect. 
- Spot A is locked and can not be captured by blue, until B was captured by blue.
- Spot B is locked and can not be captured by red, until B was captured by red.

**Comment by sepulzera** [comment]
Some more thoughts on this:

![screenshot_locks_1](https://user-images.githubusercontent.com/43857716/50546631-09db3a00-0c2b-11e9-9b23-4ecbca18cc48.jpg)
![screenshot_locks_2](https://user-images.githubusercontent.com/43857716/50546632-0c3d9400-0c2b-11e9-9485-400550030487.jpg)
![screenshot_locks_3](https://user-images.githubusercontent.com/43857716/50546633-0e9fee00-0c2b-11e9-9826-130285ee9090.jpg)

**Comment by Fisico** [comment]
![image](https://user-images.githubusercontent.com/329471/50547996-a6aad100-0c45-11e9-97b8-ca012ae52ba5.png)
