### ISSUE TITLE
Neutral state only at the beginning of the Match

### ISSUE THREAD

**Issue by Fisico** [teeworlds-domination/domination#18]
The neutral state should not be in the capturing process. The controlpoints should change from red to blue  and vice versa. At the game start spot B, D and C should be neutral. Maybe add a server command to enable it?

**Comment by sepulzera** [comment]
Removed the neutral state for conq and strike.
Neutralizing a spot is not possible anymore.
Instead, the spot will get instantly captured.

This effects the Broadcast, Capturing, Spots (they eventually display 2 flags now) and WinTimer (will start now if a team holds all spots, but at least 1 is getting captured).
