### ISSUE TITLE
Teeworlds Topic

### ISSUE THREAD

**Issue by sepulzera** [teeworlds-domination/domination#44]
[Mod] Conquest and Domination

# FIRST POST

![headerlogo](https://user-images.githubusercontent.com/329471/52237246-51f41900-28c9-11e9-8239-56405fe8385e.png)

Yeah fighting for 2 flags is nice and pretty fun, but have you ever battled for five domination spots? Our mod "Domination" sets new standards for team matches in Teeworlds, introducing new team strategies, advancing the map control, adding bloody battles and finally providing great survival experience.

~~It is a team-based mod wich introduces a new game element called [Domination Spots](https://github.com/teeworlds-domination/domination/wiki/Domination-Spot).~~ 
Each map can have up to 5 Domination Spots they are initially neutral, but can be captured by any team. Their effect on scoring varies based on the chosen gametype. You can find all relevant information about the different gametypes in their wiki pages or in the post below:
* [Gametype: Domination](https://github.com/teeworlds-domination/domination/wiki/Gametype:-Domination)
* [Gametype: Kill Domination](https://github.com/teeworlds-domination/domination/wiki/Gametype:-Kill-Domination)
* [Gametype: Conquest](https://github.com/teeworlds-domination/domination/wiki/Gametype:-Conquest)
* [Gametype: CS:DOM](https://github.com/teeworlds-domination/domination/wiki/Gametype:-CS:DOM)

### Getting started
To just play some matches, you don't need to download anything. This mod does not require any client modification.  There are official server available running the different gametypes. Just join and have fun! 
* “[Fisico] Official Domination Server”
* “[Fisico] Official Conquest Server”
* “[Fisico] Official CS:DOM Server”

Of course you can also host your own server and even create your own maps. Check out the [wiki](https://github.com/teeworlds-domination/domination/wiki/Server-Setup) for more information!

### More information
For more information like server hosting, mapping and many more specific things see the wiki page on Github.
* Wiki: https://github.com/teeworlds-domination/domination/wiki
* Offical Github Repository: https://github.com/teeworlds-domination

### Credits
* Currently this mod is being developed by Slayer and Fisico. 
* Originally it was written by ziltoide and Oy.
* Special thanks go to aQua for the Domination Spot mapres.

### Suggestions, bugs, etc.

If you think you have found a bug, or if you have a suggestion for the mod, you can create a ticket on [GitHub](https://github.com/teeworlds-domination/domination). Make sure to be as descriptive as possible, because the more information you can provide, the easier it is to do something about your bug report or feature request.

### Downloads
[Download](https://github.com/teeworlds-domination/domination/releases) Page on Github

# SECOND POST

~~### Gametype: Domination~~
![dom_logo](https://user-images.githubusercontent.com/329471/52179680-8b4f5a80-27dd-11e9-8733-724266bba543.png)

* Servers running this gametype will display DOM as gametype.
* ~~Capture the domination spots for your team by remaining in the capture area around the flags~~
* ~~Domination spots have 3 states:~~
   * ~~Neutral: no team gains points~~
   * ~~Red: red team gains points for this spot~~
   * ~~Blue: blue team gains points for this spot~~
* ~~If multiple player of one team capture together, the capturing runs faster~~
* Each captured Domination Spot increases the teamscore over time.
* Spawning: Players spawn near their own spots, otherwise on a random spawn point on the map.
* Win condition: The game will end when a team will reach the score limit or the time is over.
* The ninja powerup doubles the capture speed.
 

### Gametype: Kill Domination
~~Kill Domination is a small variation of the default Domination gametype.~~
Server running this gametype will display KDOM as gametype.
~~Capturing control points works as in Domination.~~
Control points won’t generate score points over time. Instead, each control point adds a team score every time the owning team strikes a kill.
* Team has 0 control points: + 0 score
* Team has 1 control points: + 1 score
* Team has 2 control points: + 2 score
* Team has 3 control points: + 3 score
* Team has 4 control points: + 4 score
* Team has 5 control points: + 5 score

~~### Gametype: Conquest~~
![conq_logo](https://user-images.githubusercontent.com/329471/52179620-0106f680-27dd-11e9-9cdf-9d44913765b6.png)

* Conquest is a more complex modification of the default Domination gametype.
* Servers running this gametype will display CONQ as gametype.
* Each team starts with one control point (red: A, blue: E).
* Locks: Each team can only capture its next spot (red: A -> B -> D; blue: E -> D -> C ...).
* Spawning: You will always spawn behind your team’s last control point. By default, the respawn delay is set to 10 seconds.
* Win condition: The first team owning all spots wins. If the time runs out, the team with more active control points wins.
* ~~The ninja powerup doubles the capture speed.~~

![conq](https://user-images.githubusercontent.com/329471/52234793-cd9e9780-28c2-11e9-943c-1ba523c0c7e3.png)

~~### Gametype: CS:DOM~~

![csdom_logo](https://user-images.githubusercontent.com/329471/52179613-f51b3480-27dc-11e9-8d3d-dfb73157d30b.png)

CS:DOM is a more complex modification of the default [Domination gametype](https://github.com/teeworlds-domination/domination/wiki/Gametype:-Domination). This gametype got inspired by another very popular shooter and works similary at its core. But it is not meant to be an exact copy. There are no new weapons, no hand grenades, no buy menu ... . 

Instead, it reuses existing Teeworlds Vanilla plus Domination functionality to give you a very own experience. This being said, think of CS:DOM as a better survival gametype, that is finally really fun! 

Server running this gametype will display _CS:DOM_ as gametype.

Quick facts:
* _Weapons_: You have to pick a weapon within 10 seconds. After that time, all weapon pickups get removed. The amount of maximum ammo varies (Shotgun: 10; Grenade: 7; Laser: 5). Beside that, the weapons are still the same.
* _Ammo_: You can pick up ammo to refill your weapon. Ammo can be used to refill any primary weapon (Shotgun, Grenade, Laser). 
<br>This is how ammo looks ingame (yes, it is the graphics for laser ammo):
<br> ![Ammo ingame](https://user-images.githubusercontent.com/43857716/51076964-c6a7af00-169f-11e9-9b1a-c86f2a7bf9c2.jpg)
* _Spawning_: You spawn in your base with 10 hearts and 10 armor.
* _Survival_: There is no respawn, neither for player nor for pickups.
* _Halftime_: After half of the match the teams get swapped.
* _Death_: You will drop your remaining ammo (max 4).
* _Objectives_:
   * Red has to take the flag(bomb) to a domination spot and capture it.
   * Blue has to prevent that, or neutralize the spot.
* _Timelimits_:
   * 2 minutes for red to capture the spot.
   * 40 seconds for blue to neutralize the spot again.
* _Win conditions_:
   * Blue kills all red before they capture the spot -> blue wins.
   * Red fails to capture the spot within the 2 minutes -> red wins.
   * Blue neutralizes the spot within the 40 seconds -> blue wins.
   * Blue fails to neutralize the spot -> it explodes and red wins.<br>![Screenshot of a spot exploding](https://user-images.githubusercontent.com/43857716/51077041-176bd780-16a1-11e9-8fe9-dbfe28d3032f.jpg)

**Comment by sepulzera** [comment]
1. I would prefer a stunning image as opener in the top of the first post, instead of a replication of the gametype logos (eventually improve this later).
2. The first sentence is lame and should be replaced with some more interesting introduction.
3. Credits > "Originally" should be linked to the old Domination Teeworlds Forum Thread.
4. Binary downloads for the latest release should be linked in the first post.
5. Rename all remaining occurrences *control point(s)* to *domination spot(s)*.
6. The Ninja double capture speed is not CONQ exclusive.
7. The CONQ image is not very descriptive for CONQ.

**Comment by Fisico** [comment]
1. kind of fixed.
2. "Domination spots have been placed on a Teeworlds Server near you!"
3. fixed in bbcode version
4. fix in bbcode version when released
5. fixed in bbcode version
6. fixed in bbcode version
7. fixed

**Comment by Fisico** [comment]
posted
